<?php

namespace app\admin\controller;

use app\common\model\ArticleTag;
use \app\common\model\Category;
use \app\common\model\Tag;

class Article extends Common {
    protected $db;

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }

    //文章列表
    public function index() {
        $field = $this->db->getAll();
        $this->assign('field', $field);
        return $this->fetch();
    }

    //添加文章
    public function store() {
        if (request()->isPost()) {
            $res = $this->db->store(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg'], 'index');
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }
        // 获取分类数据
        $cateData = (new Category())->getAll();
        $this->assign('cateData', $cateData);
        // 获取标签数据
        $tagData = (new Tag())->select();
        $this->assign('tagData', $tagData);
        return $this->fetch();
    }

    // 删除到回收站
    public function delToRecycle() {
        $id = input('param.id');
        if ($this->db->save(['is_del' => 1], ['id' => $id])) {
            $this->success('操作成功', 'index');
            exit;
        } else {
            $this->error('操作失败');
            exit;
        }
    }

    // 放回文章列表（移出回收站）
    public function outToRecycle() {
        $id = input('param.id');
        if ($this->db->save(['is_del' => 0], ['id' => $id])) {
            $this->success('操作成功', 'recycle');
            exit;
        } else {
            $this->error('操作失败');
            exit;
        }
    }

//    // 修改文章是否显示
//    public function changeShow() {
//        if (request()->isAjax()) {
//            $res = $this->db->changeShow(input('post.'));
//            if ($res['valid']) {
//                $this->success($res['msg'], 'index');
//                exit;
//            } else {
//                $this->error($res['msg']);
//                exit;
//            }
//        }
//    }

    // 编辑
    public function edit() {
        if (request()->isPost()) {
            $res = $this->db->edit(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg']);
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }
        $id = input('param.id/d');

        // 1、获取分类数据
        $cateData = (new Category())->getAll();
        $this->assign('cateData', $cateData);

        // 2、获取标签数据
        $tagData = (new Tag())->select();
        $this->assign('tagData', $tagData);

        // 3、获取文章信息
        $oldData = $this->db->find($id);
        //  a、为兼容之前编辑器保存内容，在输出到 js 的时候将回车换号替换为空，即写成一行
        //$oldData['content'] = str_replace(PHP_EOL, '', $oldData['content']);
        //  b、把双引号替换为单引号
        //$oldData['content'] = str_replace("\"", '\'', $oldData['content']);
        $oldData['content'] = stripslashes($oldData['content']);
        $this->assign('oldData', $oldData);

        // 4、获取文章标签
        $tagIds = (new ArticleTag())->where('article_id', $id)->column('tag_id');
        $this->assign('tagIds', $tagIds);
        return $this->fetch();
    }

    // 回收站列表
    public function recycle() {
        $field = $this->db->getAll(1);
        $this->assign('field', $field);
        return $this->fetch();
    }

    // 删除文章
    public function del() {
        $res = $this->db->del(input('post.id/d'));
        if ($res['valid']) {
            $this->success($res['msg'], 'recycle');
            exit;
        } else {
            $this->error($res['msg']);
            exit;
        }
    }
}
