<?php

namespace app\admin\controller;

class Tag extends Common {
    //
    protected $db;

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Tag();
    }

    // 标签列表
    public function index() {
        // 查询所有数据 并且每页显示5条数据
        $tags = $this->db->paginate(6);
        $this->assign('tags', $tags);
        return $this->fetch();
    }

    // 添加标签、编辑标签
    public function store() {
        $tag_id = input('param.id');
        if (request()->isPost()) {
            $res = $this->db->store(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg'], 'index');
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }

        if ($tag_id) {
            // 有 ID 则为编辑
            $oldData = $this->db->find($tag_id);
        } else {
            $oldData = ['tag_name' => ''];
        }
        $this->assign('oldData', $oldData);
        return $this->fetch();
    }

    // 删除标签
    public function del() {
        $res = $this->db->del(input('get.id'));
        if ($res['valid']) {
            $this->success($res['msg'], 'index');
            exit;
        } else {
            $this->error($res['msg']);
            exit;
        }
    }
}
